export const CHANGE_GOAL_TYPE_ROWS = "CHANGE_GOAL_TYPE_ROWS";
export const CHANGE_GOAL_TYPE_STITCHES = "CHANGE_GOAL_TYPE_STITCHES";
export const CHANGE_GOAL_TARGET = "CHANGE_GOAL_TARGET";
export const RESET_GOAL_FORM = "RESET_GOAL_FORM";
