//For goal form reducer:
export const CHANGE_GOAL_TYPE_ROWS = "CHANGE_GOAL_TYPE_ROWS";
export const CHANGE_GOAL_TYPE_STITCHES = "CHANGE_GOAL_TYPE_STITCHES";
export const CHANGE_GOAL_TARGET = "CHANGE_GOAL_TARGET";
export const RESET_GOAL_FORM = "RESET_GOAL_FORM";

//For counter reducer:
export const CHANGE_COUNTER_INCREMENT = "CHANGE_COUNTER_INCREMENT";
export const ADD_TO_COUNTER = "INCREMENT_COUNTER";
export const SUBTRACT_FROM_COUNTER = "DECREMENT_COUNTER";
export const RESET_CURRENT_COUNT = "RESET_CURRENT_COUNT";
